### ISSUE TITLE
[BDFDB causes right click context menu entires dont apper and causes crashes on right click on server list] - BDFDB

### ISSUE THREAD

**Issue by BlueStarBRS** [mwittrien/BetterDiscordAddons#2294]
**Describe the bug**
context menu entires of every devilbro plugins dont apper also when you right click meber on the server list your DS crashes also plugin/theme repo dont work while theme repo also crash discord if you click on it

**Screenshots**
![image](https://user-images.githubusercontent.com/25110093/229588661-471be5d0-f4b8-450f-935d-fffdf710e1ba.png)

**Discord Build (stable, ptb or canary):**
all on latest no diffrence between cannary or stable

**Additional context**
seems there is many stuff broken also like imageutilities

**Comment by BlueStarBRS** [comment]
Additional context
but that's just a theory from me:

![image](https://user-images.githubusercontent.com/25110093/229589813-dc070f0e-dfdf-41c8-b958-8fc8471e6c05.png)

**Comment by mwittrien** [comment]
Crash was fixed

Context Menu Items not being added is an Issue with BD

**Comment by BlueStarBRS** [comment]
> Crash was fixed
> 
> Context Menu Items not being added is an Issue with BD

nice that means i whas rigth thts sick thanks for the fix Mirco

**Comment by BlueStarBRS** [comment]
> Crash was fixed
> 
> Context Menu Items not being added is an Issue with BD

hm it seems that only the plugin repo page works now but the other stuff still happens to me
