### ISSUE TITLE
[BUG] - DiscordRecolor - Discord becomes extremely laggy and slow.

### ISSUE THREAD

**Issue by gyrobreaker** [mwittrien/BetterDiscordAddons#2890]
**Describe the bug**
When using Discord with Betterdiscord, turning on the DiscordRecolor theme causes Discord to become incredibly slow and laggy. Happens on both Linux (Mint specifically) and Windows systems on separate hardware and internet connections. Lagginess stops when switched off or when using another theme.

**To Reproduce**
When does the bug occur.
Download or turn on the DiscordRecolor theme(with another theme already applied or not). Discord will become slow and laggy. Turn it off or switch to a different theme, and Discord will be fast/normal.

**Expected behavior**
When turning on DiscordRecolor, I expected the performance to be the same as it is usually. This lagginess only occurred recently, and no other time. Has been tested with two different people in two different continents, likely not an internet issue.

**Screenshots**
N/A

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.
Stable, Betterdiscord(+ctl) stable to their latest versions.
**Additional context**
N/A

**Comment by Willy-JL** [comment]
can confirm this also happens with SettingsIcons theme, even when not inside the settings menu. scrolling channels and typing in chat box become basically unusable

**Comment by mwittrien** [comment]
Please record a video of the issue

**Comment by Frontear** [comment]
> Please record a video of the issue

Here's a quick video I was able to grab of it happening on Legcord: <https://streamable.com/m5jwqg>

**Comment by MDashK** [comment]
I can confirm this also happens with BasicBackground v1.0.5 theme plugin.

**Comment by mwittrien** [comment]
> > Please record a video of the issue
> 
> Here's a quick video I was able to grab of it happening on Legcord: https://streamable.com/m5jwqg

Video isnt available

**Comment by Frontear** [comment]
Here's an mp4 version, in hindsight this is where I should've uploaded it anyways. You can see that I demonstrate 0 enabled plugins and themes, indicating the issue solely occurs from enabling DiscordRecolor (cannot confirm if other themes by you are affected though).

https://github.com/user-attachments/assets/6301aaea-a037-49d9-bedd-5adcfee33159

**Comment by mwittrien** [comment]
Fixed might need a discord reload in some minutes

**Comment by bandithedoge** [comment]
I'm still getting these slowdowns. Looks like `SettingsIcons.css` is causing them.
