### ISSUE TITLE
[BUG] - BadgesEverywhere v1.5.6

### ISSUE THREAD

**Issue by amazman** [mwittrien/BetterDiscordAddons#431]
**Describe the bug**
Switching text channels or servers discord freezes for a few seconds

**To Reproduce**
Enabling BadgesEverywhere and switching servers

**Expected behavior**
To not lag as I switch over

**Screenshots**
N/A

**Discord Built (stable, ptb or canary):**
Stable

**Additional context**
Was working fine yesterday, just started happening today

**Comment by mwittrien** [comment]
fixed

**Comment by NPCtom** [comment]
Hey @mwittrien, I'm still experiencing sever lag when using BadgesEverywhere v1.7.6

Usually when scrolling through channels, settings page, server list etc. 

Is there a fix for this? Or is that just something that occurs when rendering many icons in on the fly??

**Comment by mwittrien** [comment]
Cant be fixed, a small lag is to be expected
