### ISSUE TITLE
[BUG] - FriendNotifications

### ISSUE THREAD

**Issue by Dschogo** [mwittrien/BetterDiscordAddons#626]
**Describe the bug**
Notifications appear everytime a status updates (like rocketleage the timer/goals)

**To Reproduce**
Friend needs to update their rich presence (only part of it)

**Expected behavior**
Only shows notifications when switching game (maybe option in settings to enable only title change or part change) 

**Discord Built (stable, ptb or canary):**
Not related to version

**Additional context**
I think it's self explaining

**Comment by Dschogo** [comment]
There was an update today with this kind of update message. Gonna wait a day to verify if its really fixed.

**Comment by mwittrien** [comment]
Yeah should fix it, since now only the game/song/activity name and details are checked and not stuff like the game time or anything else that constantly changes

**Comment by Dschogo** [comment]
Maybe need to reopen this issue :(

Its still happening with for example "unrailed!"

![image](https://user-images.githubusercontent.com/36862419/105225079-5b322b00-5b5e-11eb-9780-6cd196e438dc.png)

Meters are changing over time (all 10 secs) and its again notification spam.

Maybe just really enter an option for only checking titles?

**Comment by mwittrien** [comment]
Ill keep it closed and ill

**Comment by mwittrien** [comment]
Yeh ill fix it tomorrow

**Comment by mwittrien** [comment]
Should be fixed now, i removed the details and state from the check
