### ISSUE TITLE
ShowHiddenChannels broken

### ISSUE THREAD

**Issue by yorik100** [mwittrien/BetterDiscordAddons#72]
It simply doesn't work at all, nothing else to say

**Comment by Firecul** [comment]
Has it worked for you before, when did it stop?
It was working fine for me as of 20 hours ago

**Comment by AyanamiRei1** [comment]
Yep no longer works for me either it "loads" into BetterDiscord but it no longer shows hidden channels or shows the roles for allowed channels pretty much the thing doesn't work for me anymore.

**Comment by ImmortalZypther** [comment]
It's been fixed now, but showing roles won't work for allowed channels

**Comment by Liz-chan** [comment]
Still not working for me. Whenever I go to open the category it looks like it opens but it doesn't show anything, and if you click it again it disappears. Still seems like it's broken atm sadly.
