### ISSUE TITLE
[BUG] - 0BDFDB.plugin.js Errors on Canary

### ISSUE THREAD

**Issue by Wolfhound905** [mwittrien/BetterDiscordAddons#937]
**Describe the bug**
Crashes Better Discord Canary

**To Reproduce**
Version Canary 89738 (f4f5e08) and BetterDiscord 1.2.0 (both are latest)
I am also using the latest version of the BDFDB Lib

**Expected behavior**
No crashing.

**Discord Build:**
Canary 89738 (f4f5e08)
BetterDiscord 1.2.0

**Additional context**
I removed all my plugins and tried them one at a time. I found that the 0BDFDB.plugin.js was the one crashing the client when it was trying to be loaded. I do not know where the logs are but If you tell me I will update this bug.

**Comment by MiiArtisan** [comment]
happens to me as well

**Comment by RobotHanzo** [comment]
Can reproduce, relevant error log: `[2021-07-12 03:43:39.924][CONSOLE:ERROR] [BDFDB] (v1.7.4) Fatal Error: Could not initiate Library! TypeError: LibraryModules.UserStore.getCurrentUser is not a function`

**Comment by mwittrien** [comment]
Fixed, redownload the Library

**Comment by MiiArtisan** [comment]
still doesnt work for me :|

**Comment by RobotHanzo** [comment]
Still not fixed, error changed to `[2021-07-12 05:31:02.813][CONSOLE:ERROR] [BDFDB] (v1.7.5) Fatal Error: "after" callback of default in DiscordTag TypeError: LibraryModules.StringUtils.upperCaseFirstChar is not a function`

**Comment by MiiArtisan** [comment]
oh nice thank god its not just me

**Comment by mwittrien** [comment]
Well maybe wait till github updated the file on their servers

**Comment by MiiArtisan** [comment]
kk

**Comment by RobotHanzo** [comment]
> Well maybe wait till github updated the file on their servers

After ensuring the file I copied is the latest by comparing the commit logs it is still not fixed and gave more errors
```
[2021-07-12 05:37:21.651][CONSOLE:ERROR] [BDFDB] (v1.7.5) Fatal Error: "after" callback of default in DiscordTag TypeError: LibraryModules.StringUtils.upperCaseFirstChar is not a function
[2021-07-12 05:37:21.688][CONSOLE:ERROR] [BDFDB] (v1.7.5) Fatal Error: "after" callback of componentDidUpdate in PrivateChannel TypeError: LibraryModules.StringUtils.upperCaseFirstChar is not a function
[2021-07-12 05:37:22.096][CONSOLE:ERROR] [BDFDB] (v1.7.5) Fatal Error: "before" callback of render in BlobMask TypeError: InternalComponents.LibraryComponents.Animations.Controller is not a constructor
[2021-07-12 05:37:22.097][CONSOLE:ERROR] [BDFDB] (v1.7.5) Fatal Error: "after" callback of render in BlobMask TypeError: Cannot read property 'rect' of undefined
```

**Comment by MiiArtisan** [comment]
downloaded latest version
crash no longer happens but gives me the errors that are in the message up me

**Comment by MiiArtisan** [comment]
pls fix :<

**Comment by mwittrien** [comment]
I am busy

**Comment by MiiArtisan** [comment]
ok then

**Comment by keatonbuilder** [comment]
Can reproduce, works fine on the normal Discord client, and crashes the Canary client.

**Comment by mwittrien** [comment]
The crash was already fixed with 1.7.5

**Comment by RobotHanzo** [comment]
> The crash was already fixed with 1.7.5

The crash isn't fixed for me, still crashes on canary

**Comment by Wolfhound905** [comment]
Using the newest version I no longer am experiencing any crashes. Thanks for the fix @mwittrien 👍

**Comment by Wolfhound905** [comment]
Canary has updated again and there seems to be an issue with the PluginRepo.plugin.js on version Canary 89757 (80b09f6)
